name: Android Feature

on:
  push:
    branches:
      - '*'
      - '!develop'
      - '!master'
      - '!release/*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Screenshots android tests
        run: bash ./gradlew compileOffScreenshotsAndroidTestSources --stacktrace --info -PtestBuildType=screenshots

      - name: Unit tests
        run: bash ./gradlew testOffDebugUnitTest --stacktrace

