name: Fastlane Supply checks

on:
  push:
    branches:
      - '*'
      - '!develop'
      - '!master'
      - '!release/*'
      - '!update-workflows'
jobs:
  checks:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      
      - name: Checks
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v1
        with:
          fastlaneDir: ./fastlane # optional. default is './fastlane'
